mysql -uanton -p"bIt*rAD()" altium < alt.sql
mysql -uanton -p"bIt*rAD()" supik < sup.sql
mysql -uanton -p"bIt*rAD()" enterprise < ent.sql
mysql -uanton -p"bIt*rAD()" constructives < con.sql
mysql -uanton -p"bIt*rAD()" solidworks < sol.sql
mysql -uanton -p"bIt*rAD()" schemagee < sch.sql
mysql -uanton -p"bIt*rAD()" devices < dev.sql
mysql -uanton -p"bIt*rAD()" tb < tb.sql
mysql -uanton -p"bIt*rAD()" sys < sys.sql